dist: trusty
jobs:
  include:
  - stage: build docker image
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u liambindle --password-stdin
    - docker build . --build-arg BASE_IMAGE=ubuntu --build-arg BASE_IMAGE_TAG='16.04' -t "liambindle/penelope:$(date '+%g.%m')-ubuntu"
    - docker push "liambindle/penelope:$(date '+%g.%m')-ubuntu"
  - stage: test
  - script: docker run --rm "liambindle/penelope:$(date '+%g.%m')-ubuntu" cat hello.txt
env:
  matrix:
    secure: oEsObq4dN7RAYC3BQRBAlG4mfWZHbIGHbG0ecm9mFLpyGDYXhvg4qhzVnFM17RSp7WrQfAZ83c0vTKqrd3JajYtnFVHK1lUfewzDe8n4c4PdroFSa4x2OS5ToNs2oUEfo5oRrb1gdPMtLGLC+bCgsX4mtN8g2v+oNxmM43w8BqW4UfRqSZMZjOfd391yJN8u7xcE6qlzwie57C2PCQO33MvUZtpgURIX6DNk1wMQyc0QFwqlIPllZ27cwSzxmIxblQEYzztA24oo7xpiMlww4/vSF4YAqeLqES3rYi3lY22EvBbd8Kl7nyTMloeBgMtAIqHmL1ln067BI2q1Jlis97ayhGhdfgUwAbCpdriCuKabqKcfNMMmbp9lFVW0U59HL6x2Gg7PUDUqItcBc9GGYRsKiVXU7q+Y8D9xjd2ufOTNcY8Ab+8xP85xRiiD6AVUfueuC3kI9jQq105MtocFRAfPKcZlZt0ai24ELTVykObOZHH0Hzy4G1uz7kia7XUQNOeIC/+v/TRF+xyg4/QMlnkT91EtgBfcKUzE7XFHidSE4An9gg8o4zRCX6jiULvT7N1crCmftobpe42PQtHV4YqH6UGPynpVbkrfqa/BSgvnpSDNM+NJMkF2yeFTdURFPgSqG9c4aiI5wcwaRlWzk39qyo1kYeAfdC8xrcuI1y4=
