dist: trusty
env:
  global:
    secure: vZPxL/gPVcjlZDELVsEgjhSr9gkIFjeJtpJ0UfxI1oZHlnkXol3Howxz7JWFYHinMYZvsDvrxR49aFr+UtNhHNz2iUGAFgfvETLhVfjQrack789fJZAgPqyie5LgDIcpLmBOqk8/Wd1S5+1jg+VoMHnbUba+HevnQucnaIStp+im2s3/RZk8YUjHFYbB7dbXUwN7G+wlrXiDx98hN7QbeVoD5cBw9C8sIinec6gqmSf+nMl4aw0YgR8y6+Hc/ErQj+zgOhjP6p78Crse5kepBB994yZXXCLQFoNWtD1yJUO6G3VPmOnLc+03ZrLHhkZjy0C2G29fulMCrxxAMwkSWoDayEA90iAxkY8Jb+L+7UFckBA4VbO6FTbXcIaPGj3G/xGsepA0jMpnzg1Q5vNUFL6lxdYcujUxhXG5cELTvuLF9XwR4jJmCEPQdhNcbXyIHAho70RBsFFflKiZZrb01nFGibVIU/8+fftCmw3YbcIuv7vRxlN2W2x37E9FAeWVar1barEmS8YcX2TAFlMgR6ZGHeI+nJHTwCKIpQ6KYAKriR5uxsoNUZCjJNxB4WYlGPo5XyXY26retOp+7KZbu5KgnW1ViyyfT3fQtMHK7f/1DLfx85+aXoDL+7G+xG2JYrDB/x/PPCPUm7eT2Z3gRWKAObHGLi01sS53IBOP59U=
jobs:
  include:
  - stage: build docker image
    script:
    - echo $DOCKER_USERNAME
    - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
    - docker build . --build-arg BASE_IMAGE=ubuntu --build-arg BASE_IMAGE_TAG='16.04'
      -t "liambindle/penelope:$(date '+%g.%m')-ubuntu"
    - docker push "liambindle/penelope:$(date '+%g.%m')-ubuntu"
  - stage: test
  - script: docker run --rm "liambindle/penelope:$(date '+%g.%m')-ubuntu" cat hello.txt
