language: ruby

services:
  - docker

env:
  - secure: utBr0Jc3t3Z/Ah8YYq5d6ZCH5BG44nu6d6zOsXXBoG82hhmGvW9k9hVqgqxllx8qrx1iZHYitu0ZB6+GREvbJ7Lsx0sG1pBDvP2SZoT5FUpryC6wDvfV+Vn8Ubwye0xzxvA6E7REnIlXPMJydGb73VjU01g8CcG9kJm0MULjLLA3ZlrmCkO/qzMPVFN3/5AOnln3OQBn5BrHO1n7OuGpTSwXfLOCJxZutT5xqX2yvNwBBzu3Jk50c6AYr7ege9CJh0K7/xGDmWjV6sZYmhD5DJyUk7bUV+O0MJd4iU0zJXkpgFZ+eK3Yq/4GaXN3zeRsaYAklvLowiqbZaWApZWUzxK7ATNQOt9ruz8fnh5lU26bSio1qyvKOul5RnEUtNlFZvZPzuiUqVm23vkdB7MlkDW4XIxShZfRUNgwrMnDJ/uL+l/VwZ81BRhF7NUx4R7lFGvrLVnoYtrvPrXb7PBlslpYZ9R35sZgZa1dHcFHIGPC6JQgUww30KZSpVtYiHp6RGTwIxXP2MwcHPrZCPEYZH5ejiOYUnqgHg4I9qUHtcWYKWvkVfzQokdQOWfkSnMvoskKlKu9QeVTip7NWjt7emDeWno0FcTYFM1rHJqw/vCS8P7rFp0v/XiiDmy0qDv2yxP3jqUGAYiT8nRJqzba7syPpltb9ZBYFr4lCtGGdn4=
  
jobs:
  include:
  - stage: build docker image
    script:
    - echo $DOCKER_USERNAME
    - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
    - docker build . --build-arg BASE_IMAGE=ubuntu --build-arg BASE_IMAGE_TAG='16.04'
      -t "liambindle/penelope:$(date '+%g.%m')-ubuntu"
    - docker push "liambindle/penelope:$(date '+%g.%m')-ubuntu"
  - stage: test
  - script: docker run --rm "liambindle/penelope:$(date '+%g.%m')-ubuntu" cat hello.txt
