language: ruby
services:
- docker
jobs:
  include:
  - stage: build docker image
    script:
    - set -e
    - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
    - docker build . --build-arg BASE_IMAGE=ubuntu --build-arg BASE_IMAGE_TAG='16.04'
      -t "liambindle/penelope:$(date '+%g.%m')-ubuntu"
    - docker push "liambindle/penelope:$(date '+%g.%m')-ubuntu"
  - stage: test
  - script: docker run --rm "liambindle/penelope:$(date '+%g.%m')-ubuntu" cat hello.txt
